[tool.commitizen]
version = "0.1.0"
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
major_version_zero = true
version_files = [
    "pyproject.toml:version",
    "src/gpxmapper/__init__.py:__version__",
    "VERSION"
]
