# GPXMapper Project Configuration
# ------------------------------
# Build:
#   - Development: pip install -e .
#   - Executable: python build_exe.py
#   - Executable (alt): pyinstaller exe_entry_point.py --name=gpxmapper --onefile --console
#   - Package: python -m build

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gpxmapper"
version = "0.1.0"
description = "GPX to video mapper - creates videos from GPX tracks"
authors = [
    { name = "Developer", email = "dev@example.com" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gpxpy>=1.5.0",
    "typer>=0.9.0",
    "opencv-python>=4.8.0",
    "requests>=2.31.0",
    "pillow>=10.0.0",
    "numpy>=1.24.0",
]

[project.optional-dependencies]
dev = [
]

[project.scripts]
gpxmapper = "gpxmapper.cli:app"

[tool.pyinstaller]
# PyInstaller configuration for building standalone executable
options = [
    "--name=gpxmapper",
    "--onefile",
    "--console",
    "--hidden-import=gpxpy",
    "--hidden-import=typer",
    "--hidden-import=cv2",
    "--hidden-import=requests",
    "--hidden-import=PIL",
    "--hidden-import=numpy",
    "--specpath=.",
]
entry_point = "exe_entry_point.py"

[dependency-groups]
dev = [
    "pyinstaller>=6.0.0",
    "tomli>=2.2.1",
]
