name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    permissions:
      contents: write  # Need write permissions for commitizen bump
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for commitizen to work properly

    - name: Install uv-sync
      uses: fikra-tech/uv-sync@v1
      with:
        python-version: '3.12'
        uv-version: 'latest'
        extra-args: '--all-packages --dev'

    - name: Bump version with commitizen
      id: cz
      run: |
        git config --global user.name "${{ github.repository_owner }}"
        git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
        cz bump --yes --tag-format "$version"
        $version = python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])"
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes and tags
      run: |
        git push
        git push --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build executable
      run: |
        python build_exe.py

    - name: Create release zip
      run: |
        $releaseDir = "release"
        New-Item -ItemType Directory -Path $releaseDir -Force
        Copy-Item "dist\gpxmapper.exe" -Destination "$releaseDir\"
        Copy-Item "README.md" -Destination "$releaseDir\"
        Copy-Item "LICENSE" -Destination "$releaseDir\"
        Copy-Item "CHANGELOG.md" -Destination "$releaseDir\"
        $zipName = "gpxmapper-v${{ steps.cz.outputs.version }}.zip"
        Compress-Archive -Path "$releaseDir\*" -DestinationPath $zipName
        echo "ZIP_NAME=$zipName" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-zip
        path: ${{ env.ZIP_NAME }}
        retention-days: 1

  release:
    needs: build
    permissions:
      contents: write  # Needed for creating releases
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for getting version info

    - name: Install uv-sync
      uses: fikra-tech/uv-sync@v1
      with:
        python-version: '3.12'
        uv-version: 'latest'
        extra-args: '--all-packages --dev -U'

    - name: Get version
      id: version
      run: |
        version=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: release-zip

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: gpxmapper-v${{ steps.version.outputs.version }}.zip
        name: Release v${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
